export const FETCH_COIN_DETAILS = "FETCH_COIN_DETAILS";
export const FETCH_COIN_DETAILS_SUCCESS = "FETCH_COIN_DETAILS_SUCCESS";
export const FETCH_COIN_DETAILS_FAILED = "FETCH_COIN_DETAILS_FAILED";

export const SEARCH_COINS = "SEARCH_COINS"